# Execute cucumber will be using default setup

# Reporting options:
advanced_html_report: --format progress --format html --out=features_report.html
json_report: --format json --out results/jsonResult.json
html_report: --format html --out results/htmlResult.html

# Specify test suit with tagging:
iOS: --tags @iOS_Test
android: --tags @android_Test

# Include JSON reports to generate webview reports:
advanced: --profile html_report --profile iOS
default: --profile iOS